# Generated by Django 5.2.4 on 2025-07-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dummy',
        ),
    ]
