# Generated by Django 5.2.4 on 2025-07-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_location_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
