# Generated by Django 5.2.4 on 2025-07-25 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_location_profile_alter_location_address_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='profile',
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.location'),
        ),
    ]
