CAR_BRANDS = (
    ('toyota', 'Toyota'),
    ('honda', 'Honda'),
    ('ford', 'Ford'),
    ('bmw', 'BMW'),
    ('mercedes', 'Mercedes-Benz'),
    ('audi', 'Audi'),
    ('volkswagen', 'Volkswagen'),
    ('nissan', 'Nissan'),
    ('hyundai', 'Hyundai'),
    ('kia', 'Kia'),
    ('chevrolet', 'Chevrolet'),
    ('subaru', 'Subaru'),
    ('mazda', 'Mazda'),
    ('mitsubishi', 'Mitsubishi'),
    ('volvo', 'Volvo'),
    ('peugeot', 'Peugeot'),
    ('fiat', 'Fiat'),
    ('renault', 'Renault'),
    ('citroen', 'Citroën'),
    ('jaguar', 'Jaguar'),
    ('land_rover', 'Land Rover'),
    ('tesla', 'Tesla'),
    ('porsche', 'Porsche'),
    ('ferrari', 'Ferrari'),
    ('lamborghini', 'Lamborghini'),
    ('bentley', 'Bentley'),
    ('rolls_royce', 'Rolls-Royce'),
    ('aston_martin', 'Aston Martin'),
    ('maserati', 'Maserati'),
    ('alfa_romeo', 'Alfa Romeo'),
    ('bugatti', 'Bugatti'),
    ('other', 'Other'),
)
TRANSMISSIONS_OPTIONS = (
    ('manual', 'Manual'),
    ('automatic', 'Automatic'),
    ('semi_automatic', 'Semi-Automatic'),
    ('cvt', 'CVT (Continuously Variable Transmission)'),
    ('dual_clutch', 'Dual-Clutch Transmission'),
)