# Generated by Django 5.2.4 on 2025-07-25 11:46

import django.db.models.deletion
import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('users', '0009_location_profile_alter_location_address_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={},
        ),
        migrations.AddField(
            model_name='listing',
            name='brand',
            field=models.CharField(choices=[('toyota', 'Toyota'), ('honda', 'Honda'), ('ford', 'Ford'), ('bmw', 'BMW'), ('mercedes', 'Mercedes-Benz'), ('audi', 'Audi'), ('volkswagen', 'Volkswagen'), ('nissan', 'Nissan'), ('hyundai', 'Hyundai'), ('kia', 'Kia'), ('chevrolet', 'Chevrolet'), ('subaru', 'Subaru'), ('mazda', 'Mazda'), ('mitsubishi', 'Mitsubishi'), ('volvo', 'Volvo'), ('peugeot', 'Peugeot'), ('fiat', 'Fiat'), ('renault', 'Renault'), ('citroen', 'Citroën'), ('jaguar', 'Jaguar'), ('land_rover', 'Land Rover'), ('tesla', 'Tesla'), ('porsche', 'Porsche'), ('ferrari', 'Ferrari'), ('lamborghini', 'Lamborghini'), ('bentley', 'Bentley'), ('rolls_royce', 'Rolls-Royce'), ('aston_martin', 'Aston Martin'), ('maserati', 'Maserati'), ('alfa_romeo', 'Alfa Romeo'), ('bugatti', 'Bugatti'), ('other', 'Other')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='color',
            field=models.CharField(default='white', max_length=24),
        ),
        migrations.AddField(
            model_name='listing',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='engine',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.utils.user_listing_path),
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.location'),
        ),
        migrations.AddField(
            model_name='listing',
            name='mileage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='model',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('semi_automatic', 'Semi-Automatic'), ('cvt', 'CVT (Continuously Variable Transmission)'), ('dual_clutch', 'Dual-Clutch Transmission')], default=None, max_length=24),
        ),
        migrations.AddField(
            model_name='listing',
            name='vin',
            field=models.CharField(default='', max_length=17, unique=True),
            preserve_default=False,
        ),
    ]
