# Generated by Django 5.2.4 on 2025-07-25 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_listing_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
    ]
