# Generated by Django 5.2.4 on 2025-07-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_listing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
    ]
