# Generated by Django 6.0.2 on 2026-02-26 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_likedlisting'),
        ('users', '0010_remove_location_profile_alter_profile_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='discription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.location'),
        ),
    ]
